"use client";

import { Bot, CalendarDays, CheckCircle2, ChevronRight, Download, ExternalLink, FileText, GitCompareArrows, MoreHorizontal, Search, ShieldAlert, X } from "lucide-react";
import Link from "next/link";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { demoRepository } from "@/repositories/demo-repository";
import { useDemoStore } from "@/stores/demo-store";
import type { CompanyYearRecord, EvidenceItem } from "@/types";

type Tab = "overview" | "evidence" | "facts" | "ratings" | "history";

export default function CompanyDetailPage() {
  const { id } = useParams<{ id: string }>();
  const search = useSearchParams();
  const router = useRouter();
  const [company, setCompany] = useState<CompanyYearRecord | null>(null);
  const [items, setItems] = useState<EvidenceItem[]>([]);
  const [pdfOpen, setPdfOpen] = useState(false);
  const tab = (search.get("tab") ?? "overview") as Tab;
  const evidenceId = search.get("evidence");
  const { toggleCompare, compareIds, openDrawer, selectCompany, selectEvidence, notify, showToast } = useDemoStore();

  useEffect(() => { demoRepository.getCompany(id).then(setCompany); demoRepository.listEvidence(id).then(setItems); selectCompany(id); }, [id, selectCompany]);
  useEffect(() => { if (evidenceId) selectEvidence(evidenceId); }, [evidenceId, selectEvidence]);
  if (!company) return <div className="page"><div className="skeleton skeleton-header"/><div className="panel skeleton-panel"/></div>;
  const currentEvidence = items.find((item) => item.id === evidenceId) ?? items[0];

  function setTab(next: Tab, evidence?: string) { const query = new URLSearchParams(search.toString()); query.set("tab", next); if (evidence) query.set("evidence", evidence); router.replace(`/companies/${id}?${query}`); }
  function openEvidence(evidence: string) { selectEvidence(evidence); setTab("evidence", evidence); }
  function exportSummary() {
    if (!company) return;
    const text = `演示数据：企业、事件、报告与指标均为合成内容，不代表任何真实主体。\n\n${company.companyName} 研究摘要\n综合风险：${company.riskScore}/100\n证据完整度：${company.evidenceCoverage}%\n主要原因：未验证目标\n`;
    const url = URL.createObjectURL(new Blob([text], { type: "text/plain;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = `${company.companyId}-research-demo-${new Date().toISOString().slice(0,10)}.txt`; a.click(); URL.revokeObjectURL(url);
    notify("研究摘要已导出", `${company.companyName}合成研究摘要已生成。`); showToast("研究摘要已导出");
  }

  return <div className="page company-detail-page">
    <header className="company-header"><div className="breadcrumbs"><Link href="/companies">企业</Link><ChevronRight size={13}/><span>{company.companyName}</span></div><div className="company-title-row"><div><div className="company-title"><h2>{company.companyName}</h2><span className="demo-badge">DEMO DATA</span></div><p><code>{company.stockCode}</code> · {company.industry} · 虚构交易所 · 报告年度 2025</p></div><div className="header-actions"><button className="secondary-button" onClick={() => { if (!toggleCompare(company.companyId)) showToast("最多同时比较 5 家"); }}><GitCompareArrows size={15}/>{compareIds.includes(company.companyId) ? "移出对比" : "加入对比"}</button><button className="secondary-button" onClick={exportSummary}><Download size={15}/>导出摘要</button><button className="primary-button" onClick={() => { selectEvidence(currentEvidence?.id ?? "ev-2"); openDrawer("review"); }}><ShieldAlert size={15}/>发起复核</button><button className="icon-button" title="更多操作" aria-label="更多操作"><MoreHorizontal/></button></div></div><div className="company-meta"><span>报告发布日 <code>{company.publishDate}</code></span><span>数据版本 <code>{company.versions.data}</code></span><span>评分版本 <code>{company.versions.model}</code></span><span>最后复核 <code>2026-07-18</code></span></div></header>
    <section className="risk-summary-band"><button><span>综合风险</span><strong className="risk-score">{company.riskScore}<small>/100</small></strong><em>高风险，建议优先复核</em></button><button><span>证据完整度</span><strong className="risk-score">{company.evidenceCoverage}%</strong><i className="coverage-segments"><b/><b/><b className="missing"/></i></button><button><span>复核状态</span><strong><CheckCircle2 size={18}/>部分复核</strong><em>仍有 3 项待处理</em></button><button onClick={() => openEvidence("ev-2")}><span>主要原因</span><strong>未验证目标</strong><em>定位报告证据 →</em></button></section>
    <nav className="tabs" aria-label="企业分析视图">{[["overview","总览"],["evidence","报告证据"],["facts","外部事实"],["ratings","评级分歧"],["history","历史变化"]].map(([key,label]) => <button className={tab === key ? "active" : ""} onClick={() => setTab(key as Tab)} key={key}>{label}</button>)}</nav>
    {tab === "overview" && <Overview company={company} onEvidence={openEvidence} />}
    {tab === "evidence" && <EvidenceView items={items} current={currentEvidence} onSelect={(item) => { selectEvidence(item.id); setTab("evidence", item.id); }} onAI={() => openDrawer("ai")} onReview={() => openDrawer("review")} onPdf={() => setPdfOpen(true)} />}
    {tab === "facts" && <FactsView onReview={(evidence) => { selectEvidence(evidence); openDrawer("review"); }} />}
    {tab === "ratings" && <RatingsView />}
    {tab === "history" && <HistoryView />}
    {pdfOpen && <div className="modal-scrim"><section className="modal pdf-modal" role="dialog" aria-modal="true" aria-label="模拟 PDF 查看器"><header><div><FileText size={17}/><h3>2025 可持续发展报告（合成）</h3><code>第 {currentEvidence?.page ?? 42} 页</code></div><button className="icon-button" onClick={() => setPdfOpen(false)} aria-label="关闭 PDF 查看器"><X/></button></header><div className="pdf-toolbar"><button className="secondary-button">上一页</button><span>{currentEvidence?.page ?? 42} / 86</span><button className="secondary-button">下一页</button></div><div className="pdf-page"><span>GREENLENS SYNTHETIC REPORT</span><h3>环境目标与行动进展</h3><p>公司计划在 2030 年前显著提高低碳材料占比，并持续优化生产环节的环境表现。</p><p className="pdf-highlight">当前披露未包含可核验的基准年、阶段目标或第三方鉴证范围。</p><p>本页全部文字为前端演示生成，不来自任何真实企业或报告。</p><small>42</small></div></section></div>}
  </div>;
}

function Overview({ company, onEvidence }: { company: CompanyYearRecord; onEvidence: (id: string) => void }) {
  return <div className="detail-grid"><section className="panel"><header className="panel-header"><div><h3>风险贡献</h3><p>竖线为行业中位，不与证据质量混合</p></div></header><div className="panel-body contribution-list large">{company.components.map((component) => <button className="contribution-row contribution-button" key={component.code} onClick={() => onEvidence(component.evidenceIds[0])}><span className="contribution-meta"><span>{component.label}</span><span>{component.value} · 贡献 {component.contribution}</span></span><span className="bar-track"><span className="bar-fill" style={{ width: `${component.value}%` }}/><span className="bar-benchmark" style={{ left: `${component.industryMedian}%` }}/></span></button>)}</div></section><section className="panel"><header className="panel-header"><div><h3>2021-2025 风险变化</h3><p>年度口径 · 不做月度插值</p></div></header><div className="trend-chart" aria-label="2021 至 2025 年风险趋势"><div className="trend-axis"><span>80</span><span>60</span><span>40</span><span>20</span></div><svg viewBox="0 0 420 210" role="img"><polyline points="20,160 115,132 210,145 305,92 400,54"/><circle cx="20" cy="160" r="4"/><circle cx="115" cy="132" r="4"/><circle cx="210" cy="145" r="4"/><circle cx="305" cy="92" r="4"/><circle cx="400" cy="54" r="5"/><line x1="305" x2="305" y1="35" y2="182"/><text x="283" y="25">外部事件</text></svg><div className="trend-years"><span>2021</span><span>2022</span><span>2023</span><span>2024</span><span>2025</span></div><button className="text-button">查看数据表</button></div></section><section className="panel evidence-table-panel"><header className="panel-header"><div><h3>关键证据</h3><p>3 条声明 · 2 条外部事实 · 1 个缺失项</p></div></header><div className="evidence-rows"><button onClick={() => onEvidence("ev-2")}><i className="warning"/><span><strong>2030 年目标缺少基准年与阶段目标</strong><small>报告第 42 页 · 未验证目标</small></span><ChevronRight/></button><button onClick={() => onEvidence("ev-3")}><i className="pending"/><span><strong>范围三排放未提供可比数据</strong><small>报告第 47 页 · 量化缺失</small></span><ChevronRight/></button><button><i className="danger"/><span><strong>排放许可记录发生核算边界变更</strong><small>外部事实 · 需确认相关性</small></span><ChevronRight/></button></div></section><section className="panel next-actions"><header className="panel-header"><h3>下一步建议</h3></header><ol><li><span>核验</span>确认 2030 年目标采用的基准年</li><li><span>比对</span>检查许可口径变更与报告边界</li><li><span>补充</span>查询第三方鉴证的覆盖范围</li></ol></section></div>;
}

function EvidenceView({ items, current, onSelect, onAI, onReview, onPdf }: { items: EvidenceItem[]; current?: EvidenceItem; onSelect: (item: EvidenceItem) => void; onAI: () => void; onReview: () => void; onPdf: () => void }) {
  if (!current) return <div className="state-panel"><FileText/><h2>暂无报告证据</h2><p>当前演示公司没有匹配的合成报告片段。</p></div>;
  return <div className="evidence-workspace"><aside className="evidence-nav"><label><Search size={15}/><input placeholder="搜索报告证据"/></label><span className="section-kicker">报告目录</span>{items.filter((item) => item.type !== "external").map((item) => <button className={current.id === item.id ? "active" : ""} key={item.id} onClick={() => onSelect(item)}><span>第 {item.page} 页</span><strong>{item.title}</strong><small>{item.type === "claim" ? "声明" : "量化指标"} · {item.status === "insufficient" ? "证据不足" : "待复核"}</small></button>)}</aside><article className="evidence-document"><header><span>第 {current.page} 页</span><button className="secondary-button" onClick={onPdf}><FileText size={14}/>查看原 PDF</button></header><div className="document-sheet"><span className="section-kicker">4.2 环境目标与行动进展</span><h3>低碳材料与供应链协同</h3><p>面对行业低碳转型，公司持续推进材料配方优化和能源效率提升。报告期内，试点产线完成多项流程改造，并在供应链协同方面形成新的工作机制。</p><p>公司计划在 <mark className="claim-mark">2030 年前显著提高低碳材料占比</mark>，并持续优化生产环节的环境表现。围绕这一方向，公司将建立内部追踪机制，定期评估实施进度。</p><p>当前披露中，<mark className="gap-mark">尚未提供基准年、阶段目标或第三方鉴证范围</mark>。相关指标将在后续报告中持续完善。</p><p>以上段落为固定合成文本，仅用于演示证据定位与复核交互。</p></div></article><aside className="evidence-explanation"><span className="status-chip pending">未验证目标</span><h3>{current.title}</h3><p>{current.excerpt}</p><dl><div><dt>命中依据</dt><dd>方向性承诺缺少可复核参数</dd></div><div><dt>缺失项</dt><dd>基准年 · 阶段目标 · 鉴证边界</dd></div><div><dt>关联事实</dt><dd><button>许可核算边界发生变更</button></dd></div></dl><div className="inline-actions"><button className="secondary-button" onClick={onReview}>加入复核</button><button className="primary-button" onClick={onAI}><Bot size={15}/>询问 AI</button></div></aside></div>;
}

function FactsView({ onReview }: { onReview: (id: string) => void }) { const [selected,setSelected] = useState(0); const facts=[{date:"2025-11-18",title:"园区排放许可记录发生口径变更",severity:"中高",source:"区域环境观察站（虚构）"},{date:"2025-06-07",title:"供应链环境数据补充说明",severity:"关注",source:"产业信息台（虚构）"}]; return <div className="facts-layout"><section className="panel event-timeline"><header className="panel-header"><h3>外部事实时间线</h3><span>事件日 ≠ 报告年</span></header>{facts.map((fact,index)=><button className={selected===index?"selected":""} onClick={()=>setSelected(index)} key={fact.date}><span><CalendarDays size={15}/>{fact.date}</span><strong>{fact.title}</strong><small>{fact.source}</small></button>)}</section><section className="panel fact-detail"><header className="panel-header"><div><h3>{facts[selected].title}</h3><p>{facts[selected].date} · {facts[selected].source}</p></div><span className="status-chip medium">{facts[selected].severity}</span></header><div className="panel-body"><p>合成事件记录显示，相关许可的核算边界在报告发布前发生调整。该事件是否影响企业年度披露，需要分别核验主体关系和时间窗口。</p><div className="fact-metrics"><div><span>主体匹配</span><strong>待确认</strong><small>名称与园区地址部分一致</small></div><div><span>环境相关性</span><strong>中等</strong><small>可能影响排放口径可比性</small></div><div><span>时间窗口</span><strong>相关</strong><small>位于当前报告周期内</small></div></div><fieldset><legend>人工判断</legend>{["相关","不相关","部分相关","无法判断"].map((label)=><button key={label} onClick={()=>onReview("ev-ext-1")}>{label}</button>)}</fieldset><a href="https://source.example.invalid" onClick={(event)=>event.preventDefault()} className="source-link">查看虚构来源 <ExternalLink size={13}/></a></div></section></div>; }
function RatingsView() { const sources=[["Northstar ESG",68],["CivicRate",42],["TerraIndex",76],["Veritas E",55]]; return <section className="panel ratings-detail"><header className="panel-header"><div><h3>多源环境评级</h3><p>分歧程度独立展示，不以均值替代原始评分</p></div></header><div className="rating-axis"><span>0</span><span>25</span><span>50</span><span>75</span><span>100</span></div>{sources.map(([source,score],index)=><div className="rating-source" key={source}><strong>{source}</strong><div><i style={{left:`${score}%`,background:["#30D5E8","#5B8CFF","#F4D35E","#E879F9"][index]}}/><span style={{left:`${score}%`}}>{score}</span></div><small>2025 · 环境维度 · 合成更新</small></div>)}<div className="method-note"><strong>如何理解分歧</strong><p>不同虚构机构采用的覆盖维度与归一化方式不同。离散程度仅作为补充证据，不直接等同于综合风险。</p></div></section>; }
function HistoryView() { const [metric,setMetric]=useState("综合风险"); return <section className="panel history-view"><header className="panel-header"><div><h3>跨年变化</h3><p>仅连接有数据年份，缺失值保留断点</p></div><select value={metric} onChange={(e)=>setMetric(e.target.value)}>{["综合风险","声明强度","外部事实","量化缺失"].map(x=><option key={x}>{x}</option>)}</select></header><div className="history-chart"><svg viewBox="0 0 760 280"><line x1="40" y1="240" x2="730" y2="240"/><polyline points="60,196 220,154 380,172 540,102 700,58"/><g><circle cx="60" cy="196" r="5"/><circle cx="220" cy="154" r="5"/><circle cx="380" cy="172" r="5"/><circle cx="540" cy="102" r="5"/><circle cx="700" cy="58" r="6"/></g><text x="45" y="265">2021</text><text x="205" y="265">2022</text><text x="365" y="265">2023</text><text x="525" y="265">2024</text><text x="685" y="265">2025</text></svg><span>{metric} · 年度口径</span></div><button className="text-button">查看数据表</button></section>; }
