"use client";

import { ChevronDown, FlaskConical, Info, ShieldCheck } from "lucide-react";
import { useState } from "react";

const methods=[
  {id:"vague",title:"模糊声明",formula:"VAGUE = directionality × missing_scope",direction:"越高表示声明越难核验",threshold:"≥ 70 进入高关注",example:"仅描述“持续提升”，未给出指标或边界。"},
  {id:"target",title:"未验证目标",formula:"UNVERIFIED_TARGET = target_strength × verification_gap",direction:"越高表示目标验证要素越少",threshold:"≥ 65 建议复核",example:"披露 2030 年目标，但缺少基准年与阶段目标。"},
  {id:"quant",title:"量化缺失",formula:"QUANT_GAP = expected_metrics - disclosed_metrics",direction:"越高表示关键量化指标缺口越大",threshold:"≥ 60 建议补证",example:"披露减排方向，但无范围三总量。"},
  {id:"external",title:"外部事实",formula:"EXTERNAL_FACT = relevance × severity × time_alignment",direction:"越高表示外部事件越值得核验",threshold:"≥ 70 进入优先区",example:"报告周期内许可口径发生变化。"},
];

export default function MethodologyPage(){const [open,setOpen]=useState("target");return <div className="methodology-layout"><aside className="method-toc"><span>本页目录</span>{["核心概念","风险组成","声明 × 事实矩阵","合成验证指标","适用边界","版本时间线"].map((item,i)=><a href={`#section-${i}`} key={item}>{item}</a>)}</aside><article className="method-document"><header><span className="demo-badge">SYNTHETIC METHOD</span><h2>方法与模型</h2><p>解释风险信号如何形成、证据质量如何独立评估，以及人工复核为何保留最终判断权。</p></header><section id="section-0"><span className="section-kicker">核心概念</span><h3>风险值不是事实概率，也不是企业判决。</h3><p>GreenLens 识别的是绿色声明与外部环境事实之间值得进一步核验的不一致信号。风险值用于排序研究注意力，不用于确认企业存在漂绿行为。</p><div className="concept-row"><div><FlaskConical/><strong>风险值</strong><p>六类不一致信号的加权入口。</p></div><div><ShieldCheck/><strong>证据完整度</strong><p>报告、事件与评级来源的覆盖情况。</p></div><div><Info/><strong>复核状态</strong><p>人工判断的进度和可追溯记录。</p></div></div></section><section id="section-1"><span className="section-kicker">风险组成</span><h3>六个维度分别保留证据入口</h3><p>每个维度的值、权重和贡献分开呈现。点击指标可展开公式、方向、阈值与合成示例。</p><div className="method-accordions">{methods.map((method)=><div className={open===method.id?"open":""} key={method.id}><button onClick={()=>setOpen(open===method.id?"":method.id)}><span><strong>{method.title}</strong><small>{method.direction}</small></span><ChevronDown/></button>{open===method.id&&<div><code>{method.formula}</code><dl><div><dt>方向</dt><dd>{method.direction}</dd></div><div><dt>阈值</dt><dd>{method.threshold}</dd></div><div><dt>合成示例</dt><dd>{method.example}</dd></div></dl></div>}</div>)}</div></section><section id="section-2"><span className="section-kicker">声明 × 事实矩阵</span><h3>高声明与高事实同时出现时优先复核</h3><div className="matrix-explainer"><div><span>外部事实强度 ↑</span><i/><b>优先复核区</b><em>绿色声明强度 →</em></div><p>X 轴表示声明强度分位，Y 轴表示外部事实强度分位。右上象限边界默认为 70/70。点的颜色表达证据状态，不表达企业好坏。</p></div></section><section id="section-3"><span className="section-kicker">合成验证指标</span><h3>验证集指标不等于单份报告可信度</h3><div className="validation-metrics"><div><span>Precision</span><strong>0.78</strong></div><div><span>Recall</span><strong>0.71</strong></div><div><span>F1</span><strong>0.74</strong></div><div><span>AUROC</span><strong>0.82</strong></div></div><p>以上数值只用于界面演示。它们描述合成验证集上的分类表现，不能解读为某一企业或报告的置信度。</p></section><section id="section-4"><span className="section-kicker">适用边界</span><h3>需要人工判断的三个位置</h3><ul><li>外部事件是否属于同一经营主体。</li><li>报告披露边界是否与事件记录可比。</li><li>缺失信息是披露不足，还是当前数据源未覆盖。</li></ul></section><section id="section-5"><span className="section-kicker">版本时间线</span><h3>模型与数据版本分开记录</h3><table><thead><tr><th>日期</th><th>版本</th><th>变化</th></tr></thead><tbody><tr><td>2026-07-21</td><td><code>GL-RISK-1.3</code></td><td>新增证据质量与风险分离展示</td></tr><tr><td>2026-07-10</td><td><code>GL-RISK-1.2</code></td><td>调整外部事实时间窗口</td></tr></tbody></table></section></article><aside className="method-aside"><span>当前版本</span><code>GL-RISK-1.3</code><dl><div><dt>数据</dt><dd>SYN-2026.07</dd></div><div><dt>报告年</dt><dd>2025</dd></div><div><dt>用途</dt><dd>前端演示</dd></div></dl></aside></div>}
